language: node_js
cache: yarn
script:
- yarn run lint
- yarn run build
deploy:
  provider: heroku
  api_key:
    secure: jvNN8XCCCyxCEoZSXrNBzI7uT4kgd/tU1RDpkcfvNoZAajQr6FqN+GakXXWXQci++aKPSeef+hJ9FOglKcOFXJrUR7cKyFniOiQ4KTdDF2rvzWVATJbzqQIcNYaqzZOGcf43ZiH7Y8oSL+BQaY7CI18rec8ZFZOh4NrtDOdidObx5hDDVzRhQYg87ZhAtbkTzegIArINwyiuGcw75E9XzrlY6QYZfEk70GSgCdjIV3XSJnv2GAO+PxA8opkHhCuzfhQeMmaDnD4AlYONERe9b31ORjhpzhF9WL0U7eVrDf0g6VqTqQn2C7Z/uDgSUq9/HPeTTbfnWawthjseqZhIug0wVtqeft4Vzphot2eUobdWyXfC87YHWFLPyNOveHVuYkaBUN+h6vEJqyd12n9FUukpZ+PrnRgyVV0yKH6LSwLwRUVAr19qu3ASWbahMha0NgPs4s9r8pKtAiwQugYZaHRL/ARZoVROAH/oN0W72cAH0B4wp2ULl1s0Ydbf0y3JNjqsv6boECWTzFJP6xp0U/J7w29PGpj+CkKUkDM/p5hJq5nr/4vPjiQDqOlX9q27XHY6VWMMIqZ1wIH1LGlLAIrE5gSxYY9ogpXQD5ceTpl2ltTO7kHHLuKNSBV3GZ74toCkGH9T8oW+y2N+kh307etdawmPNCsSn62UCIP+C3Q=
  app: learn-vuejs
